[package]
name = "netural-network-cpp"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.8"

[[bin]]
name = "mnist_mlp"
path = "mnist_mlp.rs"

[[bin]]
name = "mlp_simple"
path = "mlp_simple.rs"
